### ISSUE TITLE
MacOS Failed to load library directx.hdll

### ISSUE THREAD

**Issue by ocd-lab** [Descrout/heaps-tutorials#1]
![image](https://user-images.githubusercontent.com/79586594/132137934-209540ea-db08-430e-ab65-2ef66e6b18bf.png)

**Comment by Descrout** [comment]
Since macOS does not use directx, you should change;
`-lib hldx`
to
`-lib hlsdl`
in the compile.hxml file.

I must've compiled the Animations tutorial on windows. Changed it now.
From now on, I'll use hlsdl for each one of them.
